# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Album' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Album
  pod 'Alamofire', '4.8.1'
  pod 'AlamofireImage', '3.5.0'

  target 'AlbumTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AlbumUITests' do
    # Pods for testing
  end

end
